import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, AlertTriangle, ArrowUpRight, BarChart3, CheckCircle2, ChevronRight, ClipboardList, Clock3, MapPin, Menu, Plus, Search, ShieldAlert, Sparkles, Upload, UserRound, Wrench, X } from 'lucide-react';
import { CircleMarker, MapContainer, Popup, TileLayer } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import './styles.css';
import './dark.css';

type Role = 'Citizen' | 'Admin' | 'Engineer';
type Status = 'Reported' | 'Assigned' | 'In Progress' | 'Resolved';
type Severity = 'Low' | 'Medium' | 'High' | 'Critical';
type Complaint = { id:string; title:string; location:string; area:string; severity:Severity; status:Status; date:string; description:string; assigned?:string; image:string; completionImage?:string; confidence:number };
const seed: Complaint[] = [
 {id:'RF-1024',title:'Deep pothole near junction',location:'Anna Salai, Teynampet',area:'Teynampet',severity:'Critical',status:'In Progress',date:'18 Sep 2026',description:'Large pothole on the left lane causing sudden braking near the signal.',assigned:'Arun Kumar',image:'',confidence:94},
 {id:'RF-1021',title:'Damaged road surface',location:'OMR, Perungudi',area:'Perungudi',severity:'High',status:'Assigned',date:'17 Sep 2026',description:'Broken asphalt widening after recent rains.',assigned:'Arun Kumar',image:'',confidence:87},
 {id:'RF-1018',title:'Waterlogged road crater',location:'Velachery Main Road',area:'Velachery',severity:'High',status:'Reported',date:'16 Sep 2026',description:'Pothole is hidden by water and hazardous for two-wheelers.',image:'',confidence:89},
 {id:'RF-1014',title:'Uneven road patch',location:'GST Road, Guindy',area:'Guindy',severity:'Medium',status:'Resolved',date:'14 Sep 2026',description:'Surface needs levelling beside the bus stop.',assigned:'Meena S',image:'',confidence:78},
 {id:'RF-1010',title:'Minor crack formation',location:'ECR, Thiruvanmiyur',area:'Thiruvanmiyur',severity:'Low',status:'Resolved',date:'12 Sep 2026',description:'Small cracking observed along the edge.',assigned:'Meena S',image:'',confidence:72}
];
const engineers=['Arun Kumar','Meena S','Vignesh R','Priya N'];
const priority:Record<Severity,string>={Critical:'Highest',High:'High',Medium:'Normal',Low:'Low'};
const severityOrder:Record<Severity,number>={Critical:0,High:1,Medium:2,Low:3};
function load(){try{const x=localStorage.getItem('roadfix-data');const saved=x?JSON.parse(x):seed;return saved.map((c:Complaint)=>({...c,image:c.image?.startsWith('http')?'':c.image}))}catch{return seed}}
function App(){
 const [role,setRole]=useState<Role>('Citizen'); const [page,setPage]=useState('Dashboard'); const [tickets,setTickets]=useState<Complaint[]>(load); const [selected,setSelected]=useState<Complaint|null>(null); const [toast,setToast]=useState(''); const [mobile,setMobile]=useState(false);
 useEffect(()=>localStorage.setItem('roadfix-data',JSON.stringify(tickets)),[tickets]); useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2800);return()=>clearTimeout(t)}},[toast]);
 const nav:Record<Role,string[]>={Citizen:['Dashboard','Report Damage','My Complaints','Road Map'],Admin:['Dashboard','Complaints','City Map','Engineers','Analytics'],Engineer:['Dashboard','Assigned Repairs','Repair Map','Completed Repairs']};
 const changeRole=(r:Role)=>{setRole(r);setPage('Dashboard');setSelected(null);setMobile(false)};
 const update=(id:string,changes:Partial<Complaint>,message:string)=>{setTickets(t=>t.map(x=>x.id===id?{...x,...changes}:x));setSelected(s=>s?.id===id?{...s,...changes}:s);setToast(message)};
 const open=(c:Complaint)=>{setSelected(c);setPage('Details');setMobile(false)};
 const filtered = role==='Engineer'?tickets.filter(x=>x.assigned==='Arun Kumar'):tickets;
 return <div className="app"><aside className={mobile?'sidebar open':'sidebar'}><div className="brand"><div className="brand-icon"><Wrench size={21}/></div><span>RoadFix <b>TN</b></span></div><div className="city">SMART CITY OPERATIONS</div><nav>{nav[role].map(item=><button key={item} className={page===item?'active':''} onClick={()=>{setPage(item);setSelected(null);setMobile(false)}}>{icon(item)}<span>{item}</span></button>)}</nav><div className="roadmap"><Sparkles size={16}/><div><b>Final version</b><small>Routes, duplicates & predictions</small></div></div><div className="sidebar-user"><div className="avatar">{role[0]}</div><div><b>{role==='Engineer'?'Arun Kumar':role==='Admin'?'Kavya Iyer':'Priya Raman'}</b><small>{role} portal</small></div></div></aside>
 <main><header><button className="menu" onClick={()=>setMobile(!mobile)}><Menu/></button><div className="crumb"><span>{role} portal</span><ChevronRight size={15}/><b>{selected?'Complaint details':page}</b></div><div className="role-switch"><UserRound size={16}/><select value={role} onChange={e=>changeRole(e.target.value as Role)}>{(['Citizen','Admin','Engineer'] as Role[]).map(r=><option key={r}>{r}</option>)}</select></div></header>
 {page==='Dashboard'&&<Dashboard role={role} tickets={filtered} open={open} setPage={setPage}/>} {page==='Report Damage'&&<Report onSubmit={c=>{setTickets(t=>[c,...t]);setPage('My Complaints');setToast(`${c.id} created — assessment complete`)}}/>} {['My Complaints','Complaints','Assigned Repairs','Completed Repairs'].includes(page)&&<List page={page} role={role} tickets={page==='Completed Repairs'?filtered.filter(x=>x.status==='Resolved'):filtered} open={open}/>} {['Road Map','City Map','Repair Map'].includes(page)&&<Map tickets={filtered} open={open}/>} {page==='Engineers'&&<Engineers tickets={tickets} update={update}/>} {page==='Analytics'&&<Analytics tickets={tickets}/>} {page==='Details'&&selected&&<Details ticket={selected} role={role} update={update}/>} 
 </main>{toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}</div>}</div>
}
const icon=(x:string)=>x.includes('Dashboard')?<BarChart3/>:x.includes('Report')?<Plus/>:x.includes('Map')?<MapPin/>:x.includes('Analytics')?<Activity/>:x.includes('Engineer')?<UserRound/>:x.includes('Completed')?<CheckCircle2/>:<ClipboardList/>;
function Stats({tickets}:{tickets:Complaint[]}){const cards=[['All reports',tickets.length,ClipboardList],['Needs action',tickets.filter(x=>x.status==='Reported'||x.status==='Assigned').length,Clock3],['In progress',tickets.filter(x=>x.status==='In Progress').length,Wrench],['Resolved',tickets.filter(x=>x.status==='Resolved').length,CheckCircle2]];return <div className="stats">{cards.map(([a,b,C]:any)=><div className="stat" key={a}><div><small>{a}</small><strong>{b}</strong><em><ArrowUpRight size={13}/> 12.5% this week</em></div><div className="stat-icon"><C size={20}/></div></div>)}</div>}
function Dashboard({role,tickets,open,setPage}:{role:Role;tickets:Complaint[];open:(x:Complaint)=>void;setPage:(x:string)=>void}){const attention=[...tickets].sort((a,b)=>severityOrder[a.severity]-severityOrder[b.severity]).slice(0,4);return <section className="page"><div className="hero"><div><p className="eyebrow">18 SEPTEMBER 2026 · CHENNAI</p><h1>{role==='Admin'?'City roads, intelligently maintained.':role==='Engineer'?'Your repair operations at a glance.':'Keeping Chennai roads safer, together.'}</h1><p className="muted">{role==='Citizen'?'Report road damage in seconds and follow every step of the repair.':'Live insights from RoadFix TN’s smart maintenance network.'}</p></div>{role==='Citizen'&&<button className="primary" onClick={()=>setPage('Report Damage')}><Plus size={18}/> Report damage</button>}</div><Stats tickets={tickets}/><div className="grid-2"><div className="panel"><div className="panel-head"><div><h2>{role==='Admin'?'Priority queue':role==='Engineer'?'Today’s assignments':'Recent reports'}</h2><p>Updated in real time</p></div><button className="link" onClick={()=>setPage(role==='Citizen'?'My Complaints':role==='Admin'?'Complaints':'Assigned Repairs')}>View all</button></div><div className="ticket-list">{attention.map(t=><TicketRow key={t.id} t={t} open={open}/>)}</div></div><div className="panel map-panel"><div className="panel-head"><div><h2>Chennai live map</h2><p>{tickets.length} reported locations</p></div><MapPin className="teal"/></div><MiniMap tickets={tickets} open={open}/><button className="map-link" onClick={()=>setPage(role==='Citizen'?'Road Map':role==='Admin'?'City Map':'Repair Map')}>Open operational map <ChevronRight size={15}/></button></div></div><div className="panel ai-banner"><div className="ai-orb"><Sparkles/></div><div><b>AI assessment is actively prioritising repairs</b><p>Every road-damage report is evaluated for severity and confidence before it enters the queue.</p></div><span>{tickets.filter(x=>x.severity==='Critical'||x.severity==='High').length} urgent cases</span></div></section>}
function Evidence({image,compact=false}:{image:string;compact?:boolean}){return image?<img className={compact?'evidence-thumb':''} src={image} alt="Road damage evidence"/>:<div className={compact?'evidence-thumb evidence-empty':'evidence-empty'}><Upload size={compact?15:28}/><span>{compact?'No photo':'Photo can be uploaded by the reporter'}</span></div>}
function TicketRow({t,open}:{t:Complaint;open:(x:Complaint)=>void}){return <button className="ticket" onClick={()=>open(t)}><Evidence image={t.image} compact/><div className="ticket-main"><b>{t.title}</b><small><MapPin size={12}/>{t.location}</small></div><Badge type={t.severity}/><Badge type={t.status}/><ChevronRight className="chev" size={18}/></button>}
function Badge({type}:{type:string}){return <span className={'badge '+type.toLowerCase().replace(' ','-')}>{type}</span>}
function MiniMap({tickets,open}:{tickets:Complaint[];open:(x:Complaint)=>void}){const coords:[[number,number],...Array<[number,number]>]=[[13.032,80.240],[12.966,80.245],[12.981,80.232],[13.009,80.220],[12.987,80.260]];const color:Record<Severity,string>={Critical:'#ff3b6b',High:'#ff8a35',Medium:'#ffd43b',Low:'#20d9ff'};return <div className="mini-map live-map"><MapContainer center={[12.990,80.242]} zoom={13} scrollWheelZoom className="leaflet-map"><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{tickets.map((t,i)=><CircleMarker key={t.id} center={coords[i%coords.length]} radius={11} pathOptions={{color:'#ffffff',weight:3,fillColor:color[t.severity],fillOpacity:1}} eventHandlers={{click:()=>open(t)}}><Popup><b>{t.id}</b><br/>{t.location}<br/>{t.severity} severity</Popup></CircleMarker>)}</MapContainer><div className="map-surface"><span className="map-chip"><Activity size={12}/> LIVE ISSUE LAYER</span><span className="map-city">PERUNGUDI · CHENNAI</span></div></div>}
function Report({onSubmit}:{onSubmit:(c:Complaint)=>void}){const [file,setFile]=useState<string>('');const [desc,setDesc]=useState('');const [loc,setLoc]=useState('');const [analysing,setAnalysing]=useState(false);const [result,setResult]=useState<{s:Severity,c:number}|null>(null); const analyze=()=>{if(!file)return;setAnalysing(true);setTimeout(()=>{setResult({s:'High',c:87});setAnalysing(false)},900)};const submit=()=>{if(!file||!loc||!desc||!result)return;onSubmit({id:`RF-${1025+Math.floor(Math.random()*70)}`,title:'Road damage reported',location:loc,area:loc.split(',')[0],severity:result.s,status:'Reported',date:'18 Sep 2026',description:desc,image:file,confidence:result.c})};return <section className="page form-page"><div className="hero"><div><p className="eyebrow">CITIZEN ACTION CENTRE</p><h1>Report road damage</h1><p className="muted">Help us locate and prioritise the issue accurately.</p></div></div><div className="report-grid"><div className="panel form"><h2>Damage details</h2><p>Fields marked * are required.</p><label>Road-damage photo *</label><div className="upload">{file?<img src={file}/>:<><Upload/><b>Upload a clear photo</b><small>JPG, PNG or WEBP · max 10 MB</small></>}<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)setFile(URL.createObjectURL(f))}}/></div><label>Location *</label><input value={loc} onChange={e=>setLoc(e.target.value)} placeholder="e.g. Anna Salai, Teynampet"/><div className="location-hint"><MapPin size={16}/>Interactive location selector · Chennai demo area</div><label>Describe the problem *</label><textarea value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Tell us about the size, lane and any immediate risk..."/><button className="secondary full" disabled={!file||analysing} onClick={analyze}>{analysing?'Analysing image…':result?'Re-run AI assessment':'Analyse with RoadFix AI'} <Sparkles size={17}/></button>{result&&<div className="assessment"><Sparkles/><div><small>AI ROAD DAMAGE ASSESSMENT</small><b>{result.s.toUpperCase()} severity · {result.c}% confidence</b><p>Priority set to <strong>{priority[result.s]}</strong>. This is a prototype assessment.</p></div></div>}<button className="primary full" disabled={!result||!loc||!desc} onClick={submit}>Submit report <ArrowUpRight size={17}/></button></div><div className="panel location-card"><div className="panel-head"><div><h2>Pin location</h2><p>Tap the map to refine your report</p></div></div><MiniMap tickets={[]} open={()=>{}}/><div className="selected-location"><MapPin/><div><b>{loc||'Select a road location'}</b><small>Chennai, Tamil Nadu</small></div></div><div className="tip"><ShieldAlert size={18}/><span>For immediate danger or accidents, please contact emergency services first.</span></div></div></div></section>}
function List({page,role,tickets,open}:{page:string;role:Role;tickets:Complaint[];open:(x:Complaint)=>void}){const [query,setQuery]=useState('');const [filter,setFilter]=useState('All');let filtered=tickets.filter(t=>(t.id+t.location+t.title).toLowerCase().includes(query.toLowerCase())&&(filter==='All'||t.severity===filter||t.status===filter)); if(role==='Citizen'&&page==='My Complaints')filtered=filtered.slice(0,4);return <section className="page"><div className="title-row"><div><p className="eyebrow">{role.toUpperCase()} PORTAL</p><h1>{page}</h1><p className="muted">{filtered.length} items shown · ordered by priority</p></div></div><div className="filters"><div className="search"><Search size={18}/><input placeholder="Search ID, road or area" value={query} onChange={e=>setQuery(e.target.value)}/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Critical</option><option>High</option><option>Medium</option><option>Low</option><option>Reported</option><option>Assigned</option><option>In Progress</option><option>Resolved</option></select></div><div className="panel table-wrap"><table><thead><tr><th>COMPLAINT</th><th>LOCATION</th><th>AI SEVERITY</th><th>PRIORITY</th><th>STATUS</th><th>ASSIGNED TO</th><th/></tr></thead><tbody>{filtered.map(t=><tr key={t.id} onClick={()=>open(t)}><td><div className="table-id"><Evidence image={t.image} compact/><div><b>{t.id}</b><small>{t.date}</small></div></div></td><td>{t.location}</td><td><Badge type={t.severity}/></td><td><b>{priority[t.severity]}</b></td><td><Badge type={t.status}/></td><td>{t.assigned||<span className="muted">Unassigned</span>}</td><td><ChevronRight size={18}/></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty"><ClipboardList size={32}/><b>No matching reports</b><span>Try a different search or filter.</span></div>}</div></section>}
function Map({tickets,open}:{tickets:Complaint[];open:(x:Complaint)=>void}){return <section className="page"><div className="title-row"><div><p className="eyebrow">LOCATION INTELLIGENCE</p><h1>Chennai road issue map</h1><p className="muted">Severity-coded reports across the city.</p></div><div className="legend"><span><i className="critical"/>Critical</span><span><i className="high"/>High</span><span><i className="medium"/>Medium</span></div></div><div className="large-map"><MiniMap tickets={tickets} open={open}/><div className="map-card"><b>Active reports</b><strong>{tickets.filter(x=>x.status!=='Resolved').length}</strong><small>Click a marker for details</small></div></div></section>}
function Engineers({tickets,update}:{tickets:Complaint[];update:(id:string,c:Partial<Complaint>,m:string)=>void}){return <section className="page"><div className="title-row"><div><p className="eyebrow">WORKFORCE MANAGEMENT</p><h1>Repair teams</h1><p className="muted">Manage active field teams and workloads.</p></div></div><div className="engineers">{engineers.map((e,i)=>{const n=tickets.filter(x=>x.assigned===e&&x.status!=='Resolved').length;return <div className="panel engineer" key={e}><div className="avatar big">{e[0]}</div><div><h2>{e}</h2><p>{i===0?'Road Repair Lead':'Municipal Repair Team'}</p></div><span className={n?'available':'idle'}>{n?'On assignment':'Available'}</span><div className="workload"><span>Active assignments</span><b>{n}</b></div>{tickets.filter(x=>!x.assigned&&x.status==='Reported').slice(0,1).map(x=><button className="secondary full" onClick={()=>update(x.id,{assigned:e,status:'Assigned'},`${x.id} assigned to ${e}`)}>Assign {x.id}</button>)}</div>})}</div></section>}
function Analytics({tickets}:{tickets:Complaint[]}){const groups:['Critical'|'High'|'Medium'|'Low',number][]=(['Critical','High','Medium','Low'] as Severity[]).map(x=>[x,tickets.filter(t=>t.severity===x).length]);return <section className="page"><div className="title-row"><div><p className="eyebrow">MUNICIPAL INTELLIGENCE</p><h1>Analytics</h1><p className="muted">A clear view of maintenance demand and progress.</p></div></div><Stats tickets={tickets}/><div className="grid-2"><div className="panel chart"><h2>Complaints by severity</h2>{groups.map(([s,n])=><div className="bar-row" key={s}><Badge type={s}/><div className="bar"><i className={s.toLowerCase()} style={{width:`${Math.max(12,n/tickets.length*100)}%`}}/></div><b>{n}</b></div>)}</div><div className="panel chart"><h2>Resolution performance</h2><div className="donut"><div><strong>{Math.round(tickets.filter(x=>x.status==='Resolved').length/tickets.length*100)}%</strong><small>resolved</small></div></div><p className="center muted">Target: resolve standard issues within 72 hours</p></div></div></section>}
function Details({ticket:t,role,update}:{ticket:Complaint;role:Role;update:(id:string,c:Partial<Complaint>,m:string)=>void}){const [repair,setRepair]=useState(''); const states:Status[]=['Reported','Assigned','In Progress','Resolved'];const at=states.indexOf(t.status);return <section className="page"><button className="back" onClick={()=>history.back()}>← Back to list</button><div className="details-head"><div><p className="eyebrow">COMPLAINT {t.id}</p><h1>{t.title}</h1><p className="muted"><MapPin size={15}/>{t.location} · Reported {t.date}</p></div><div className="detail-badges"><Badge type={t.severity}/><Badge type={t.status}/></div></div><div className="details-grid"><div><div className="panel photo"><img src={t.image}/><div><b>Road-damage evidence</b><small>Uploaded by citizen</small></div></div><div className="panel timeline"><h2>Repair timeline</h2>{states.map((s,i)=><div className={i<=at?'step done':'step'} key={s}><span>{i<at?<CheckCircle2 size={16}/>:i===at?<Clock3 size={16}/>:<i/>}</span><div><b>{s}</b><small>{i===at?'Current status':i<at?'Completed':'Awaiting update'}</small></div></div>)}</div></div><div><div className="panel info"><h2>AI Road Damage Assessment</h2><div className="score"><div className={'score-ring '+t.severity.toLowerCase()}>{t.confidence}%</div><div><small>DETECTED SEVERITY</small><b>{t.severity.toUpperCase()}</b><p>Priority: <strong>{priority[t.severity]}</strong></p></div></div><p className="muted">Prototype inference: visual road-surface cues are evaluated to support municipal triage.</p></div><div className="panel info"><h2>Report information</h2><p>{t.description}</p><dl><dt>Assigned engineer</dt><dd>{t.assigned||'Awaiting assignment'}</dd><dt>Area / ward</dt><dd>{t.area}</dd></dl></div>{role==='Admin'&&!t.assigned&&<div className="panel action"><h2>Assign repair team</h2><select onChange={e=>e.target.value&&update(t.id,{assigned:e.target.value,status:'Assigned'},`${t.id} assigned to ${e.target.value}`)} defaultValue=""><option value="" disabled>Select an engineer</option>{engineers.map(e=><option key={e}>{e}</option>)}</select></div>}{role==='Engineer'&&t.assigned==='Arun Kumar'&&t.status!=='Resolved'&&<div className="panel action"><h2>Update repair status</h2><div className="action-buttons">{t.status==='Assigned'&&<button className="primary full" onClick={()=>update(t.id,{status:'In Progress'},`${t.id} is now in progress`)}>Start repair <Wrench size={16}/></button>}{t.status==='In Progress'&&<><input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)setRepair(URL.createObjectURL(f))}}/><button className="primary full" onClick={()=>update(t.id,{status:'Resolved',completionImage:repair},`${t.id} marked resolved — citizen notified`)}>Mark resolved <CheckCircle2 size={16}/></button></>}</div></div>}</div></div></section>}
createRoot(document.getElementById('root')!).render(<App/>);
